server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass https://node-js-production-defe.up.railway.app;
    }

    # Fallback: proxy all non‑static requests to backend
    location @backend {
        proxy_pass https://node-js-production-defe.up.railway.app;
    }
}