server {
    listen 80;
    server_name localhost;

    # Serve static files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ @backend;
    }

    location /api/ {
        proxy_pass http://node-js-production-defe.up.railway.app;
    }

    # Fallback: proxy all non‑static requests to backend
    location @backend {
        proxy_pass http://node-js-production-defe.up.railway.app;
    }
}