
services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "7878:7878"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      rust-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/health"]
      interval: 10s
      timeout: 5s
      retries: 5



  rust-service:
    build: ./Rust-Services/conflict-checker   # adjust path to the specific Rust project
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5



  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: lumecraft
      MYSQL_DATABASE: classroom_reservations

    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: